
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - webapp.webapp.ivyxjc.com
  resources:
  - webdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.webapp.ivyxjc.com
  resources:
  - webdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.webapp.ivyxjc.com
  resources:
  - webdeployments/status
  verbs:
  - get
  - patch
  - update
