# permissions for end users to view webdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webdeployment-viewer-role
rules:
- apiGroups:
  - webapp.webapp.ivyxjc.com
  resources:
  - webdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.webapp.ivyxjc.com
  resources:
  - webdeployments/status
  verbs:
  - get
