apiVersion: webapp.webapp.ivyxjc.com/v1
kind: WebDeployment
metadata:
    name: webdeployment-sample
spec:
    deployment:
        replicas: 3
        selector:
            matchLabels:
                app: nginx
        template:
            metadata:
                labels:
                    app: nginx
            spec:
                containers:
                    -   name: nginx
                        image: nginx:1.14.2
                        ports:
                            -   containerPort: 80